"""The OpenAPI document is the API's documentation, so it gets tested like the
API does.

These are completeness checks rather than snapshot tests: prose should be free
to improve without a test failing, but a new endpoint that arrives undocumented
-- or a parameter added without a description -- should not slip through
silently. Anything a caller could reasonably assume is documented, assert on.
"""

import pytest
from fastapi.testclient import TestClient

from api import app

client = TestClient(app)

SPEC = app.openapi()
DATA_PATHS = [p for p in SPEC["paths"] if p.startswith("/api/v1")]


def operations():
    for path, item in SPEC["paths"].items():
        for method, operation in item.items():
            if isinstance(operation, dict):
                yield path, method, operation


def test_served_over_http():
    r = client.get("/api/openapi.json")
    assert r.status_code == 200
    assert r.json()["info"]["title"] == "CuckooTrade"


def test_front_matter_orients_a_reader():
    info = SPEC["info"]
    assert info["summary"] and info["description"]
    # The cross-cutting contracts a caller cannot discover per-endpoint.
    for topic in ("Quickstart", "determinism", "as_of", "scenario", "synthetic"):
        assert topic in info["description"], f"description never mentions {topic}"
    assert SPEC["servers"] and SPEC["externalDocs"]["url"]


def test_every_operation_is_described():
    for path, method, operation in operations():
        where = f"{method.upper()} {path}"
        assert operation.get("summary"), f"{where} has no summary"
        assert operation.get("description"), f"{where} has no description"
        assert operation.get("operationId"), f"{where} has no operationId"
        assert operation.get("tags"), f"{where} is untagged"


def test_operation_ids_are_readable_and_unique():
    """They become method names in generated SDKs, so FastAPI's autogenerated
    `stock_bars_api_v1_alpaca_v2_stocks_bars_get` is not good enough."""
    ids = [op["operationId"] for _, _, op in operations()]
    assert len(ids) == len(set(ids))
    assert not any("_get" in name or "_api_" in name for name in ids)


def test_every_parameter_is_described():
    for path, method, operation in operations():
        for param in operation.get("parameters", []):
            assert param.get("description"), (
                f"{method.upper()} {path} parameter {param['name']!r} has no description"
            )


def test_documented_tags_all_exist():
    declared = {tag["name"] for tag in SPEC["tags"]}
    used = {tag for _, _, op in operations() for tag in op.get("tags", [])}
    assert used <= declared, f"undeclared tags in use: {used - declared}"
    for tag in SPEC["tags"]:
        assert tag.get("description")


def test_every_schema_ref_resolves():
    defined = set(SPEC["components"]["schemas"])
    found = set()

    def walk(node):
        if isinstance(node, dict):
            if ref := node.get("$ref"):
                found.add(ref.rsplit("/", 1)[-1])
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    walk(SPEC)
    assert found <= defined, f"dangling $refs: {found - defined}"
    assert defined <= found, f"unreferenced schemas: {defined - found}"


def test_schema_fields_carry_descriptions():
    """A bar's `vw` or `n` means nothing without a sentence saying so."""
    for name, schema in SPEC["components"]["schemas"].items():
        for field, spec in schema.get("properties", {}).items():
            assert spec.get("description") or spec.get("properties"), (
                f"{name}.{field!r} has no description"
            )


@pytest.mark.parametrize("path", DATA_PATHS)
def test_scenario_is_documented_on_every_data_endpoint(path):
    """scenario= is applied by middleware, so no route declares it -- which is
    exactly how it stayed invisible in the document before."""
    for method, operation in SPEC["paths"][path].items():
        names = {p["name"] for p in operation.get("parameters", [])}
        assert "scenario" in names, f"{path} does not document scenario="


@pytest.mark.parametrize("path", DATA_PATHS)
def test_marking_headers_and_rate_limit_are_documented(path):
    """Also middleware-produced, and equally undiscoverable otherwise."""
    for method, operation in SPEC["paths"][path].items():
        assert "429" in operation["responses"], f"{path} does not document its 429"
        headers = operation["responses"]["200"]["headers"]
        for name in ("X-Cuckoo-Synthetic", "X-Cuckoo-Generation", "RateLimit-Limit"):
            assert name in headers, f"{path} does not document {name}"


def test_health_is_not_documented_as_rate_limited():
    """The probe is the one path the limiter exempts; saying otherwise would
    send someone chasing a 429 that cannot happen."""
    operation = SPEC["paths"]["/api/health"]["get"]
    assert "429" not in operation["responses"]
    assert "RateLimit-Limit" not in operation["responses"]["200"]["headers"]


def test_bar_endpoints_document_the_restatement_headers():
    for path in ("/api/v1/alpaca/v2/stocks/bars",
                 "/api/v1/alpaca/v2/stocks/bars/latest",
                 "/api/v1/alpaca/v2/stocks/{symbol}/bars"):
        headers = SPEC["paths"][path]["get"]["responses"]["200"]["headers"]
        assert "X-Cuckoo-As-Of" in headers and "X-Cuckoo-Restated" in headers


def test_success_responses_carry_worked_examples():
    for path, method, operation in operations():
        content = operation["responses"]["200"].get("content", {})
        for media, body in content.items():
            assert body.get("examples"), f"{path} 200 {media} has no example"


def test_wire_compat_surfaces_document_their_own_error_shape():
    """An injected fault wears the mimicked provider's error shape; the document
    has to agree, or it teaches the wrong parser."""
    expected = {
        "/api/v1/alpaca/v2/stocks/bars": "AlpacaError",
        "/api/v1/polygon/v2/aggs/ticker/{ticker}/prev": "PolygonError",
    }
    for path, schema_name in expected.items():
        content = SPEC["paths"][path]["get"]["responses"]["400"]["content"]
        assert content["application/json"]["schema"]["$ref"].endswith(schema_name)


def test_alphavantage_documents_that_errors_arrive_as_200():
    """The single most surprising thing about that surface. If the document does
    not say it, someone writes `raise_for_status()` and never sees the error."""
    operation = SPEC["paths"]["/api/v1/alphavantage/query"]["get"]
    assert "400" not in operation["responses"]
    body = operation["responses"]["200"]
    assert "200" in body["description"]
    assert any(
        "Error Message" in str(ex["value"])
        for ex in body["content"]["application/json"]["examples"].values()
    )


def test_examples_are_valid_against_their_declared_shape():
    """Cheap structural check: a documented example that disagrees with its own
    schema is worse than no example."""
    bars = SPEC["paths"]["/api/v1/alpaca/v2/stocks/bars"]["get"]
    required = set(SPEC["components"]["schemas"]["AlpacaBar"]["required"])
    for name, ex in bars["responses"]["200"]["content"]["application/json"]["examples"].items():
        value = ex["value"]
        assert set(value) == {"bars", "next_page_token"}, name
        for series in value["bars"].values():
            for bar in series:
                assert set(bar) == required, f"{name}: bar fields drifted from AlpacaBar"


def test_documented_defaults_match_the_running_code():
    """Defaults are the part of a document people trust without checking."""
    params = {
        p["name"]: p
        for p in SPEC["paths"]["/api/v1/alpaca/v2/stocks/bars"]["get"]["parameters"]
    }
    assert params["timeframe"]["schema"]["default"] == "1Day"
    assert params["sort"]["schema"]["default"] == "asc"
    assert params["generation"]["schema"]["default"] == 1
    assert params["symbols"]["required"] is True


def test_enums_are_documentation_only():
    """The schemas advertise closed value sets so Swagger renders a dropdown,
    but validation must stay with the handlers -- their errors teach, and
    FastAPI's 422 would not match the provider's error shape."""
    r = client.get("/api/v1/alpaca/v2/stocks/bars?symbols=AAPL&sort=sideways")
    assert r.status_code == 400
    assert "sort=asc" in r.json()["message"]


def test_document_still_validates_after_post_processing():
    """finalize() mutates the document after FastAPI has already validated it,
    so nothing downstream would catch a malformed injection. SDK generators
    would."""
    from fastapi.openapi.models import OpenAPI

    OpenAPI.model_validate(SPEC)


def test_nulls_survive_into_the_examples():
    """get_openapi() strips every null on its way out, which quietly deleted the
    one field the pagination examples exist to show. finalize() puts them back."""
    examples = (
        SPEC["paths"]["/api/v1/alpaca/v2/stocks/bars"]["get"]["responses"]["200"]
        ["content"]["application/json"]["examples"]
    )
    assert examples["ordinary"]["value"]["next_page_token"] is None
    assert examples["paginated"]["value"]["next_page_token"] is not None
    assert "\u0000" not in str(SPEC), "a NULL sentinel leaked into the document"


def test_links_point_at_operations_that_exist():
    """Link objects name an operationId and feed it a runtime expression. A
    typo in either is invisible until a tool tries to follow it."""
    ids = {op["operationId"] for _, _, op in operations()}
    params_by_id = {
        op["operationId"]: {p["name"] for p in op.get("parameters", [])}
        for _, _, op in operations()
    }
    found = 0
    for path, method, operation in operations():
        for status, body in operation["responses"].items():
            for name, spec in body.get("links", {}).items():
                found += 1
                target = spec["operationId"]
                assert target in ids, f"{path} link {name!r} targets unknown {target!r}"
                for param in spec["parameters"]:
                    assert param in params_by_id[target], (
                        f"{path} link {name!r} feeds {target!r} an unknown parameter "
                        f"{param!r}"
                    )
                assert spec.get("description")
    assert found >= 3, "the paging and restatement workflows should both be linked"


def test_pagination_is_expressed_as_a_link():
    links = (
        SPEC["paths"]["/api/v1/alpaca/v2/stocks/bars"]["get"]["responses"]["200"]["links"]
    )
    assert links["nextPage"]["parameters"]["page_token"] == (
        "$response.body#/next_page_token"
    )
